---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "truenas-ca"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: "truenas-ca-secret"
    template:
      engineVersion: v2
      data:
        ca.crt: "{{ .SIGNING_CERTIFICATE }}"
  dataFrom:
    - extract:
        key: kv/cluster/truenas
