---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./hr.yaml
  - ../../../../templates/volsync/
configMapGenerator:
  - name: rtorrent-flood-configmap
    files:
      - ./config/rtorrent.rc
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
