---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./sonarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./plex/ks.yaml
  - ./lidarr/ks.yaml
  - ./radarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./recyclarr/ks.yaml
  # - ./immich/ks.yaml
