---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./sonarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./jellyfin/ks.yaml
  - ./lidarr/ks.yaml
  - ./radarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./immich/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./komga/ks.yaml
  - ./mylar/ks.yaml
