---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app onlyoffice
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      onlyoffice:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          onlyoffice:
            image:
              repository: docker.io/onlyoffice/documentserver
              tag: 8.2.2
            command: ["sh", "-c", "/entrypoint-override.sh"]
            env:
              WOPI_ENABLED: "true"
              USE_UNAUTHORIZED_STORAGE: "true"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              requests:
                cpu: 50m
                memory: 1Gi
              limits:
                memory: 4Gi
    service:
      app:
        controller: onlyoffice
        ports:
          http:
            port: 80

    persistence:
      entrypoint-override:
        type: configMap
        name: onlyoffice-configmap
        defaultMode: 511
        globalMounts:
          - path: /entrypoint-override.sh
            subPath: entrypoint-override.sh
            readOnly: true
      config:
        type: configMap
        name: onlyoffice-configmap
        globalMounts:
          - path: /etc/onlyoffice/documentserver/local.dist.json
            subPath: local.json
            readOnly: true
      data:
        type: persistentVolumeClaim
        size: 5Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /etc/onlyoffice
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            add_header X-Forwarded-Proto "https";
        hosts:
          - host: onlyoffice.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
