---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./hr.yaml
configMapGenerator:
  - name: onlyoffice-configmap
    files:
      - entrypoint-override.sh=./config/entrypoint-override.sh
      - local.json=./config/local.json
generatorOptions:
  disableNameSuffixHash: true
