---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app firefly-iii-data-importer
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: firefly-iii
  values:
    controllers:
      firefly-iii-data-importer:
        containers:
          main:
            image:
              repository: fireflyiii/data-importer
              tag: version-1.3.0
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            env:
              TZ: Europe/Warsaw
              TRUSTED_PROXIES: "**"
              FIREFLY_III_URL: "http://firefly-iii.default.svc.cluster.local:8080"
              VANITY_URL: "https://money.${SECRET_DOMAIN}"
              FIREFLY_III_ACCESS_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: firefly-iii-secret
                    key: IMPORTER_KEY
              CAN_AUTO_IMPORT: 'true'
              CAN_POST_FILES: 'true'
              CAN_POST_AUTOIMPORT: 'true'
              IMPORT_DIR_ALLOWLIST: &import-dir /import
            envFrom:
              - secretRef:
                  name: firefly-iii-secret
    service:
      main:
        controller: firefly-iii-data-importer
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: external
        hosts:
          - host: &host firefly-iii-data-importer.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      # data:
      #   enabled: true
      #   existingClaim: firefly-iii-importer
      #   advancedMounts:
      #     firefly-iii-data-importer:
      #       main:
      #         - path: *import-dir
      config-file:
        enabled: true
        type: configMap
        name: data-importer-config
        advancedMounts:
          firefly-iii-data-importer:
            main:
              - path: /import
                readOnly: true
