---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: &name postgres
spec:
  postgresVersion: 16
  monitoring:
    pgmonitor:
      exporter:
        resources:
          requests:
            cpu: 10m
            memory: 64M
          limits:
            memory: 512M
  patroni: # turn on sync writes to at least 1 other replica
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        max_wal_size: 5GB
        synchronous_commit: "on"
        parameters:
          max_connections: 500
  instances:
    - name: postgres
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres
      replicas: &replicas 1
      dataVolumeClaimSpec:
        storageClassName: ceph-block
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
  users:
    # Superuser
    - name: "postgres"
      databases: ["postgres"]
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
    # Applications
    - name: "authentik"
      databases: ["authentik"]
      password:
        type: AlphaNumeric
    - name: "immich"
      databases: ["immich"]
      password:
        type: AlphaNumeric
    # - name: "bazarr"
    #   databases: ["bazarr"]
    #   password:
    #     type: AlphaNumeric
    # - name: "lubelog"
    #   databases: ["lubelog"]
    #   password:
    #     type: AlphaNumeric
    # - name: "gatus"
    #   databases: ["gatus"]
    #   password:
    #     type: AlphaNumeric
    # - name: "grafana"
    #   databases: ["grafana"]
    #   password:
    #     type: AlphaNumeric
    # - name: "kyoo"
    #   databases: ["kyoo"]
    #   password:
    #     type: AlphaNumeric
    # - name: "paperless"
    #   databases: ["paperless"]
    #   password:
    #     type: AlphaNumeric
    # - name: "prowlarr"
    #   databases: ["prowlarr_main"]
    #   password:
    #     type: AlphaNumeric
    # - name: "radarr"
    #   databases: ["radarr_main"]
    #   password:
    #     type: AlphaNumeric
    # - name: "readarr"
    #   databases: ["readarr_main", "readarr_cache", "readarr_log"]
    #   password:
    #     type: AlphaNumeric
    # - name: "sonarr"
    #   databases: ["sonarr_main"]
    #   password:
    #     type: AlphaNumeric
  backups:
    pgbackrest:
      configuration: &backupConfig
        - secret:
            name: crunchy-pgo-secret
      global: &backupFlag
        # Global
        compress-type: "bz2"
        compress-level: "9"
        # Minio
        repo1-block: "y"
        repo1-bundle: "y"
        repo1-path: /crunchy-pgo
        repo1-retention-full: "30" # days
        repo1-retention-full-type: "time"
        repo1-s3-uri-style: path
      manual:
        repoName: repo1
        options:
          - --type=full
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres-backup
      repos:
        - name: repo1
          s3: &minio
            bucket: crunchy-pgo
            endpoint: http://${NAS_ADDRESS}:9000
            region: us-east-1
          schedules:
            full: "30 1 * * 0" # Sunday at 01:30
            differential: "30 1 * * 1-6" # Mon-Sat at 01:30
            incremental: "30 3-23 * * *" # Every hour except 01:30-2:30
  dataSource:
    pgbackrest:
      stanza: db
      configuration: *backupConfig
      global: *backupFlag
      repo:
        name: repo1
        s3: *minio
  proxy:
    pgBouncer:
      service:
        metadata:
          annotations:
            external-dns.alpha.kubernetes.io/hostname: cpgo.${SECRET_DOMAIN}
            io.cilium/lb-ipam-ips: ${CRUNCHY_PGO_ADDRESS:=temp}
        type: LoadBalancer
      port: 5432
      replicas: 3
      config:
        global:
          # Grafana requires session
          # Ref: https://github.com/grafana/grafana/issues/74260
          pool_mode: session
          client_tls_sslmode: prefer
          default_pool_size: "100"
          max_client_conn: "500"
