---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crunchy-pgo-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: cloudnative-pg-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
       s3.conf: |
          [global]
          repo1-s3-key={{ .ACCESS_KEY }}
          repo1-s3-key-secret={{ .SECRET_KEY }}
  dataFrom:
    - extract:
        key: kv/cluster/volsync/s3
