---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crunchy-pgo-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: crunchy-pgo-secret
    template:
      engineVersion: v2
      data:
        s3.conf: |
          [global]
          repo1-s3-key={{ .ACCESS_KEY }}
          repo1-s3-key-secret={{ .SECRET_KEY }}
        encryption.conf: |
          [global]
          repo1-cipher-pass={{ .CRUNCHY_POSTGRES_BACKUP_ENCRYPTION_CIPHER }}
  dataFrom:
    - extract:
        key: kv/cluster/volsync/s3
    - extract:
        key: kv/cluster/database/crunchy-pgo
