---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.28.0-standalone-strict/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-db-init-sql
data:
  init.sql: |-
    \c immich\\
    BEGIN;
    CREATE EXTENSION vectors;
    CREATE EXTENSION earthdistance CASCADE;
    ALTER DATABASE immich SET search_path TO "$user", public, vectors;
    ALTER SCHEMA vectors OWNER TO immich;
    COMMIT;

