---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autobrr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: autobrr-secret
    creationPolicy: Owner
    template:
      data:
        AUTOBRR__SESSION_SECRET: "{{ .SESSION_SECRET }}"
  dataFrom:
    - extract:
        key: kv/cluster/media/autobrr
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autobrr-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: autobrr-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        AUTOBRR__DATABASE_TYPE: postgres
        AUTOBRR__POSTGRES_DATABASE: '{{ index . "dbname" }}'
        AUTOBRR__POSTGRES_HOST: '{{ index . "pgbouncer-host" }}'
        AUTOBRR__POSTGRES_USER: '{{ index . "user" }}'
        AUTOBRR__POSTGRES_PASS: '{{ index . "password" }}'
        AUTOBRR__POSTGRES_PORT: '{{ index . "pgbouncer-port" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-autobrr
