---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: nextcloud-data
spec:
  sourcePVC: nextcloud-data
  trigger:
    schedule: "30 2 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: nextcloud-data-volsync-secret
    volumeSnapshotClassName: ceph-block
    cacheCapacity: 1Gi
    cacheStorageClassName: ceph-block
    cacheAccessModes:
      - ReadWriteOnce
    storageClassName: ceph-block
    accessModes:
      - ReadWriteOnce
    retain:
      daily: 7
      weekly: 4
      monthly: 6
    moverSecurityContext:
      fsGroup: 82
      runAsGroup: 82
      runAsUser: 82
    customCA:
      secretName: nextcloud-data-volsync-secret
      key: ca.crt
