apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:79KSMIyPo5WMsCk1ZuCu1pB8plgb98UmDxKVZucl6IdRZONp,iv:9HYxREOcJL0RCzhfYnrRJPD+eE+dcidC/RPbHnCs7oM=,tag:klEdxsvymyfy2jw5/alBSQ==,type:str]
    TUNNEL_TOKEN: ENC[AES256_GCM,data:fXRMUTuWLNfknQ8AjyBR+i9rqa1JFqNbZ0NqVhzou3bLysGbYTOI7D9ty2vjWuI9UpTyJK+Uqc3anmaAtohQ6dss8/hsCgIMyXP2TW7UmlbvqWmm5N9Rfwl5OvyhQe98FrhdXkV56yxLy0hIL/AREqxrjILdb0QqofMY/FLvHf/v659NYfVsrlwWOFSPOXnj9hyqvWWgL1Zv71cAKpNhlc7qmuqATODRn8pzIT6PdtrTjMGx,iv:AJYASUnWCtbAs4NOvKfn8HnG4qPE1C45wlOnYVhXHPU=,tag:xZR4RKPBptok2UZojxvpiw==,type:str]
    credentials.json: ENC[AES256_GCM,data:efj8PcVoXgXaNRCs+vfz8vQSBtEyRHZzV9yJbUuYXf2B71RZFBMiis0RR8IjO3y6iF0a7SanrQsIKFDb76GAJn+OqIazitRDYZ+bHJITCvWy1ORZ0p9rLrk+cdgnPCpboa//KJZuoTn+FKbYth0UG8AHoAci73mVX4KNwdtR/m7rAEqxGxtcPo/fJA/JDR0iTuy8Y31lqqsExDSDF7ixzsaPSHGfT3Qx4ee+/NYm0g==,iv:X2Eq3qv3vn4gkv3FfFaLSrCIehBmSBiV1O+gQmBblZ8=,tag:4mpZY2MZG4Qe/9Y9bGttvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSjhHVjVoQVhLNEttTnoz
            Z2pFR3pvY1FyeDZ6Z1AwdUNkclZ2bHo4aUFzCnVkbzRKZzhHWmI1SG1TYzdHQkJ6
            bUNGODN1K0J3ZTB1Nm15MGlNRGtoU1kKLS0tIE9SZ1BvOFNSZ2pHanNOZUJtWHZW
            UWlLSUZMKzYrMWJ6WSt5REZjREpOeVEKC6hYlQBn5vuw4gF+xBEK418NXJAtbu45
            QSXEGX99kjH/Sq2nvb7ltVFuILLO90+hCy2645bjdCO7ACVxEtLRKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-09T20:46:12Z"
    mac: ENC[AES256_GCM,data:iZ353LdaCZtdNLMHrR6uWcIIGoYPubMfsAAhTT6i9OHE/xjTgNCLDQ5eI7gtJl1q7lxFyo9XlRMMNriNsI86QDDcL2x8m6ji4LJTd0s5KsvSkbauGA/gh0oLOzmTtIxmMBOVeC9VzjbXd6p0qbmgw/ZBUO3d4X9cxqVhkeF4goU=,iv:JHVGzlA43q0SV6QaehvoaQpypI6p2UnfuAbRoC61qDA=,tag:IggYd8i37kDE+3uUbTmCLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
