apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:MGtxPwv6wl7nMYu1sjDkGxTt3wlIKN4R6m+QHlT2sCPriEjH,iv:j5Fr3+QLd7ORWNdNiOPedRQPwhrN+rM+gSFKNNULwxo=,tag:/8GCWRIyyCdm/qX3ZWaeOg==,type:str]
    credentials.json: ENC[AES256_GCM,data:VhQNLOWH/sEsHj+/LhKA2RTdcVCJL9r/0lBaqJ2nT3JAEGWA+qnuNR32norh0WrhYMys7PsmmgSDsHa/T2RYcyOUIDCXFE2+hGRnGO3i6wI2hmPkvtPlWqURBgjNioUHDFeMuzR2I3Ia3NCxBqEl/aGCGYZZrOsJsD47YWKDDB94Yr1iGRnuofgeo2Q4fhz5D/91eY/bc/FkRWHy8xAHbk3dlpb8R2xJYERy2ZXJAQ==,iv:6EBBSuv4UDHNAT/cTDlJr+KszE+srqueV6bGYjtCwCk=,tag:gYWEYnDyL2NZ9xU38CRNJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBREJscE8ySys5MmFrYm1n
            QXRNSE9YS0lSTWkrNnJ5VE9COW0xb1BBOEFBCmlLK1dHTmtLWWpnNzJ6clM0WlB0
            bHI3OHFoM0lDVUNtYUVySU9Dc0t6SFEKLS0tIGxnTkUwblpqMzJkdlpEdTRGVU1z
            M0hiUUF4bEp5dUhFT3Q0Um9mZnU4MGcK/pkOZl+8A8wlCX41/5pxW25XfYXVlJOP
            bBwXne8XC3ANB2CjTaRL0f/eNtETmOLv2ARx7tUMjaiqjnWc/s6c6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-19T11:00:44Z"
    mac: ENC[AES256_GCM,data:B6/qgxM6A670hVOX/s7m65EHYoPhSirD9bPVP5vXHLuNId1SqU1wZON6ymgV1pu8EntjPR9SWo6GWN5ih8XxAUcJM1e0Ou9sqL6jdpaAiQGigSmNnx+rl009LjxG4Gi2ly/fo5IQZaCx+FLrzMBusvCel6SR8osyf+k776LVN3U=,iv:WRi4jL4I4mQFPberRqlhGKEZRaX+tTwytAlH+yxPqLE=,tag:wBXMxcCHPIZfXc4pcUcbng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
