apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://10.0.2.2:8200"
      path: "kv"
      version: "v2"
      auth:
        # https://www.vaultproject.io/docs/auth/userpass
        userPass:
          path: "userpass"
          username: "cluster"
          secretRef:
            name: "vault-secret"
            key: "password"
            namespace: external-secrets
