apiVersion: v1
data:
    password: ENC[AES256_GCM,data:iU5jZ3PkjU3KAT3ybAkf+lr9NuWpCYT2NEvjqg==,iv:PK2V49YMRlOJqRzicLTcK+eBaGlSbppeUiKxWn89HAo=,tag:oE1lIVxiKc2FZgkrvG+I7w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: vault-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibmU0V1JJL0xVaDBhQVVj
            WmpoNDdsMXhBeVlqYk5PWDNtdjgzdGpSaWpRCllVcVlZSzhBMDF4MjBQSGZpR2Qw
            MWNFYU5Tb2VUQ3o2VkhVZkRXN3EyeXMKLS0tIC84ejN1Y3dPb1IwK0VSdFFZSmgr
            MlBDODFqVGdZNE5mb2E3WHArQkxObk0KiCyBFOU7Nl3VGPBK3Rv2G7J57gMmLSmz
            xay8ZQqipAj2Ur3LtrUeEllJ53nvXAcybahpAaaUHSgZXjcSqfcerw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-14T22:55:18Z"
    mac: ENC[AES256_GCM,data:pcZ4MVm1HrBkYJJr8XBL05D300jkF8nYkLtu5Xyk9WM+bdI7+waM+MtUCdhfTBssy/P5A6oVv9N0BKryh/sOzdYC9Wk78h6AP/B3YHJuAXVjnrPnEbk72Sk9bY3ohdas5JBrR7Yy52GKkXrLfuqgl630XRWyu+GyH07K0GY8R3g=,iv:BNKJDwZpr6Up7Jvm6EvAXOQEFdsTyHZQDbQa66+ebMY=,tag:9+vTHfQPDMNoBR0e4hjlWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
