---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellyfin
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: intel-device-plugin-gpu
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      jellyfin:
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 44
              - 109
        containers:
          main:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.9.9
            resources:
              limits:
                memory: 1390Mi
                gpu.intel.com/i915: 3
            probes:
              # liveness: &probes
              #   enabled: true
              #   custom: true
              #   spec:
              #     httpGet:
              #       path: /health
              #       port: &port 8096
              #     initialDelaySeconds: 90
              #     periodSeconds: 10
              #     timeoutSeconds: 1
              #     failureThreshold: 300
              # readiness: *probes
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      main:
        controller: jellyfin
        ports:
          http:
            port: 8096
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/name: Jellyfin
          gethomepage.dev/icon: jellyfin.png
          gethomepage.dev/description: Personal Streaming
          gethomepage.dev/widget.type: jellyfin
          gethomepage.dev/widget.url: http://jellyfin.media.svc.cluster.local:8096
          gethomepage.dev/widget.key: "{{`{{HOMEPAGE_VAR_JELLYFIN_TOKEN}}`}}"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host jf.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /config
      media:
        enabled: true
        type: nfs
        server: "${NAS_ADDRESS}"
        path: "${NAS_BASE_URL}/media"
        globalMounts:
          - path: /media
      transcode:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /transcode
      cache:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /cache
