---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name matrix-synapse
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://ananace.gitlab.io/charts
      chart: matrix-synapse
      version: 3.9.11
      sourceRef:
        kind: HelmRepository
        name: ananace
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: authentik
      namespace: security
  valuesFrom:
    - kind: Secret
      name: synapse-secret
      valuesKey: values.yaml
    - kind: Secret
      name: synapse-secret
      valuesKey: postgres.yaml
  values:
    image:
      repository: ghcr.io/element-hq/synapse
      tag: v1.114.0
    serverName: ${SECRET_DOMAIN}
    publicServerName: matrix.${SECRET_DOMAIN}
    wellknown:
      enabled: true
      image:
        repository: ghcr.io/rtsp/docker-lighttpd
        tag: 1.4.76

    workers:
      default:
        resources:
          limits:
      #      cpu: 1000m # One CPU core
            memory: 1Gi
          requests:
      #      cpu: 400m # 0.4 of core
            memory: 512Mi
      media_repository:
        enabled: true
        strategy:
          type: Recreate
      federation_sender:
        enabled: true
        replicaCount: 2
      generic_worker:
        enabled: false
        generic: true
        replicaCount: 2
        listeners: [client]
        csPaths:
          ## Client API requests
          - "/_matrix/client/(api/v1|r0|v3|unstable)/createRoom$"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/publicRooms$"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/joined_members$"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/context/"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/members$"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/state$"
          - "/_matrix/client/v1/rooms/.*/hierarchy$"
          - "/_matrix/client/unstable/org.matrix.msc2716/rooms/.*/batch_send$"
          - "/_matrix/client/unstable/im.nheko.summary/rooms/.*/summary$"
          - "/_matrix/client/(r0|v3|unstable)/account/3pid$"
          - "/_matrix/client/(r0|v3|unstable)/account/whoami$"
          - "/_matrix/client/(r0|v3|unstable)/devices$"
          - "/_matrix/client/versions$"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/voip/turnServer$"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/event/"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/joined_rooms$"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/search$"

          ## Encryption requests
          - "/_matrix/client/(r0|v3|unstable)/keys/query$"
          - "/_matrix/client/(r0|v3|unstable)/keys/changes$"
          - "/_matrix/client/(r0|v3|unstable)/keys/claim$"
          - "/_matrix/client/(r0|v3|unstable)/room_keys/"

          ## Registration/login requests
          - "/_matrix/client/(api/v1|r0|v3|unstable)/login$"
          - "/_matrix/client/(r0|v3|unstable)/register$"
          - "/_matrix/client/v1/register/m.login.registration_token/validity$"

          ## Event sending requests
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/redact"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/send"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/state/"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/rooms/.*/(join|invite|leave|ban|unban|kick)$"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/join/"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/profile/"

          ## User directory search requests
          - "/_matrix/client/(r0|v3|unstable)/user_directory/search"
      synchrotron:
        enabled: true
        generic: true
        listeners: [client]
        csPaths:
          - "/_matrix/client/(v2_alpha|r0|v3)/sync$"
          - "/_matrix/client/(api/v1|v2_alpha|r0|v3)/events$"
          - "/_matrix/client/(api/v1|r0|v3)/initialSync$"
          - "/_matrix/client/(api/v1|r0|v3)/rooms/[^/]+/initialSync$"
      frontend_proxy:
        enabled: false
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      tls:
        - secretName: matrix-tls
          hosts:
            - ${SECRET_DOMAIN}
            - matrix.${SECRET_DOMAIN}

    postgresql:
      enabled: false

    extraConfig:
      presence:
        enabled: true
      enable_3pid_lookup: false

    synapse:
      strategy:
        type: Recreate
      resources:
        requests:
          cpu: 1000m
          memory: 2500Mi
        limits:
          cpu: 1000m
          memory: 2500Mi
    signingkey:
      job:
        enabled: true
      # existingSecret: matrix-synapse-signingkey
    persistence:
      enabled: true
      existingClaim: *name
