---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./es.yaml
  - ./hr.yaml
  - ../../../../templates/gatus/external
  - ../../../../templates/volsync/
configMapGenerator:
  - name: ocis-configmap
    files:
      - proxy.yaml=./resources/proxy.yaml
      - csp.yaml=./resources/csp.yaml
generatorOptions:
  disableNameSuffixHash: true
