---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq
spec:
  refreshInterval: 5m
  target:
    name: rabbitmq-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RABBITMQ_PASSWORD: "{{ .RABBITMQ_PASSWORD }}"
        RABBITMQ_ERLANG_COOKIE: "{{ .RABBITMQ_ERLANG_COOKIE }}"
  dataFrom:
    - extract:
        key: kv/cluster/database/rabbitmq
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault-backend
      rewrite:
        - regexp:
            source: "(.*)"
            target: "RABBITMQ_$1"
