---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app rabbitmq
spec:
  interval: 30m
  chart:
    spec:
      chart: rabbitmq
      version: 15.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      registry: docker.io
      repository: bitnami/rabbitmq
      tag: 4.0.5-debian-12-r0
    auth:
      username: user
      existingPasswordSecret: &secret rabbitmq-secret
      existingSecretPasswordKey: RABBITMQ_PASSWORD
      existingErlangSecret: *secret
      existingSecretErlangKey: "RABBITMQ_ERLANG_COOKIE"
    tls:
      enabled: false
