---
# yaml-language-server: $schema: https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: firefly-iii
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: firefly-iii-secret
    template:
      engineVersion: v2
      data:
        DB_USERNAME: "{{ .POSTGRES_SUPER_USER }}"
        DB_PASSWORD: "{{ .POSTGRES_SUPER_PASS }}"
        APP_KEY: "{{ .APP_KEY }}"
        MAIL_HOST: "{{ .SMTP_HOST }}"
        MAIL_PORT: "{{ .SMTP_PORT }}"
        MAIL_FROM: "{{ .MAIL_FROM }}"
        MAIL_USERNAME: "{{ .SMTP_USERNAME }}"
        MAIL_PASSWORD: "{{ .SMTP_PASSWORD }}"
        MAP_DEFAULT_LAT: "{{ .MAP_DEFAULT_LAT }}"
        MAP_DEFAULT_LONG: "{{ .MAP_DEFAULT_LONG }}"
        STATIC_CRON_TOKEN: "{{ .STATIC_CRON_TOKEN }}"
      metadata:
        labels:
          cnpg.io/reload: "true"
  dataFrom:
    - extract:
        key: kv/cluster/database/cloudnative-pg
    - extract:
        key: kv/cluster/default/firefly-iii
    - extract:
        key: kv/cluster/smtp
