---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      recyclarr:
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 1Gi
              storageClass: ceph-block
              globalMounts:
                - path: /config
        pod:
          enableServiceLinks: true
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          init-config:
            image:
              repository: public.ecr.aws/docker/library/busybox
              tag: latest@sha256:82742949a3709938cbeb9cec79f5eaf3e48b255389f2dcedf2de29ef96fd841c
              pullPolicy: IfNotPresent
            command:
              - "/bin/sh"
              - "-c"
              - "cp /tmp/config/recyclarr.yml /config/recyclarr.yml"
        containers:
          main:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 7.2.3
            env:
              TZ: America/New_York
            envFrom:
              - secretRef:
                  name: recyclarr-secret
            resources:
              limits:
                memory: 128M
    service:
      main:
        controller: recyclarr
        enabled: false

    defaultPodOptions:
      enableServiceLinks: true
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch

    persistence:
      config-file:
        enabled: true
        type: configMap
        name: recyclarr-configmap
        advancedMounts:
          recyclarr:
            init-config:
              - path: /tmp/config
                readOnly: true
