---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: sonarr-secret
    creationPolicy: Owner
    template:
      data:
        SONARR__API_KEY: "{{ .API_KEY }}"
  dataFrom:
    - extract:
        key: kv/cluster/media/sonarr
