---
# yaml-language-server: $schema=https://raw.githubusercontent.com/authelia/authelia/refs/heads/master/docs/static/schemas/v4.38/json-schema/configuration.json
# Note: Authelia vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
authentication_backend:
  ldap:
    implementation: custom
    start_tls: false
    address: ldap://lldap.security.svc.cluster.local:3890
    timeout: 5s
    base_dn: dc=zed,dc=gay
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_search_mode: filter
    attributes:
      username: uid
      display_name: displayName
      group_name: cn
      mail: mail
  password_reset:
    disable: true
  refresh_interval: 1m

access_control:
  default_policy: one_factor

identity_providers:
  oidc:
    lifespans:
      access_token: 30m
      refresh_token: 30m
    cors:
      endpoints:
        - 'authorization'
        - 'token'
        - 'revocation'
        - 'introspection'
        - 'userinfo'
    clients:
      - client_id: $${MEALIE_CLIENT_ID}
        client_name: Mealie
        client_secret: $${MEALIE_CLIENT_SECRET_DIGEST}
        public: false
        scopes:
          - openid
          - profile
          - groups
          - email
        userinfo_signed_response_alg: none
        redirect_uris:
          - "https://mealie.${SECRET_DOMAIN}/login"
          - "https://mealie.${SECRET_DOMAIN}/login?direct=1"
      - client_id: ocis
        client_name: ownCloud
        public: true
        redirect_uris:
          - "https://files.${SECRET_DOMAIN}/"
          - "https://files.${SECRET_DOMAIN}/oidc-callback.html"
          - "https://files.${SECRET_DOMAIN}/oidc-silent-redirect.html"
        scopes:
          - openid
          - profile
          - groups
          - email
      - client_id: 'xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69'
        client_name: 'ownCloud desktop client'
        client_secret: $${OWNCLOUD_CLIENT_SECRET_DESKTOP_DIGEST}
        public: false
        scopes:
          - 'openid'
          - 'groups'
          - 'profile'
          - 'email'
          - 'offline_access'
        redirect_uris:
          - 'http://127.0.0.1'
          - 'http://localhost'
      - client_id: 'e4rAsNUSIUs0lF4nbv9FmCeUkTlV9GdgTLDH1b5uie7syb90SzEVrbN7HIpmWJeD'
        client_name: 'ownCloud Android app'
        client_secret: $${OWNCLOUD_CLIENT_SECRET_ANDROID_DIGEST}
        public: false
        scopes:
          - 'openid'
          - 'groups'
          - 'profile'
          - 'email'
          - 'offline_access'
        redirect_uris:
          - 'oc://android.owncloud.com'
      - client_id: 'mxd5OQDk6es5LzOzRvidJNfXLUZS2oN3oUFeXPP8LpPrhx3UroJFduGEYIBOxkY1'
        client_name: 'ownCloud iOS app'
        client_secret: $${OWNCLOUD_CLIENT_SECRET_IOS_DIGEST}
        public: false
        scopes:
          - 'openid'
          - 'groups'
          - 'profile'
          - 'email'
          - 'offline_access'
        redirect_uris:
          - 'oc://ios.owncloud.com'
          - 'oc.ios://ios.owncloud.com'
session:
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: authelia_session
      domain: ${SECRET_DOMAIN}
      authelia_url: https://auth.${SECRET_DOMAIN}
      default_redirection_url: https://${SECRET_DOMAIN}
  redis:
    database_index: 2
    host: dragonfly.database.svc.cluster.local

notifier:
  disable_startup_check: true
  smtp:
    sender: "Authelia <authelia@${SECRET_DOMAIN}>"
    disable_require_tls: false
