---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payload
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: payload-secret
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: payload
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .PAYLOAD_POSTGRES_USERNAME }}"
        INIT_POSTGRES_PASS: "{{ .PAYLOAD_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        DATABASE_URI: "postgres://{{ .PAYLOAD_POSTGRES_USERNAME }}:{{ .PAYLOAD_POSTGRES_PASSWORD }}@postgres16-rw.database.svc.cluster.local:5432/payload"
        PAYLOAD_SECRET: "{{ .PAYLOAD_SECRET }}"
        PAYLOAD_S3_ACCESS: "{{ .PAYLOAD_S3_ACCESS  }}"
        PAYLOAD_S3_SECRET: "{{ .PAYLOAD_S3_SECRET  }}"
        PAYLOAD_S3_BUCKET: "{{ .PAYLOAD_S3_BUCKET  }}"
        PAYLOAD_S3_ENDPOINT: "{{ .PAYLOAD_S3_ENDPOINT  }}"
  dataFrom:
    - extract:
        key: kv/cluster/default/payload
    - extract:
        key: kv/cluster/database/cloudnative-pg
    # - extract:
    #     key: kv/cluster/smtp
