---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: payload-homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      payload:
        replicas: 1
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: payload-secret
        containers:
          main:
            image:
              repository: ghcr.io/zbigniewzolnierowicz/payload-home
              tag: v1.4.0
            envFrom: *envFrom
            env:
              PORT: &port 80
    service:
      main:
        controller: payload
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
        hosts:
          - host: &host "payload.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: payload
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      uploads:
        enabled: true
        existingClaim: payload-uploads
    defaultPodOptions:
      enableServiceLinks: true
      imagePullSecrets:
        - name: ghcr-secret
    podAnnotations:
      secret.reloader.stakater.com/reload: payload-homepage
