---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name authentik-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # Authentik
        AUTHENTIK_BOOTSTRAP_EMAIL: '{{ .AUTHENTIK_EMAIL }}'
        AUTHENTIK_BOOTSTRAP_PASSWORD: '{{ .AUTHENTIK_PASSWORD }}'
        AUTHENTIK_BOOTSTRAP_TOKEN: '{{ .AUTHENTIK_TOKEN }}'
        AUTHENTIK_SECRET_KEY: '{{ .AUTHENTIK_SECRET_KEY }}'
        AUTHENTIK_REDIS__DB: "1"
        AUTHENTIK_EMAIL__HOST: '{{ .SMTP_HOST }}'
        AUTHENTIK_EMAIL__PORT: '{{ .SMTP_PORT }}'
        AUTHENTIK_EMAIL__USERNAME: '{{ .SMTP_USERNAME }}'
        AUTHENTIK_EMAIL__PASSWORD: '{{ .SMTP_PASSWORD }}'
        AUTHENTIK_EMAIL__FROM: 'Authentik <cluster@${SECRET_DOMAIN}>'
        AUTHENTIK_EMAIL__USE_TLS: 'true'
  dataFrom:
  - extract:
      key: kv/cluster/security/authentik
  - extract:
      key: kv/cluster/smtp
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: authentik-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        AUTHENTIK_POSTGRESQL__NAME: '{{ .dbname }}'
        AUTHENTIK_POSTGRESQL__HOST: '{{ .host }}' # pgBouncer is set to session for Grafana, and Authentik requires transaction
        AUTHENTIK_POSTGRESQL__USER: '{{ .user }}'
        AUTHENTIK_POSTGRESQL__PASSWORD: '{{ .password }}'
        AUTHENTIK_POSTGRESQL__USE_PGBOUNCER: 'false'
        AUTHENTIK_POSTGRESQL__SSLMODE: 'require'
  dataFrom:
  - extract:
      key: postgres-pguser-authentik
