apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:UyQiIR6YL8nVDDR0LXE5fNoBSv+zj+unENtFmBjPmIHiTnqsWYq5yg==,iv:t+KkN6lZZlxaYmc7pdyR0PPF5yC6iqo7iSiKz9oOQWo=,tag:VN6TXKsNvTeqZuQDv5U7lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZXBjZklQdTd0NExreC8z
            eVcrOGRzVGVzOHJLMldtekFuMXgrczdteUY4Cjl1RTB0ejd4cnpneGQrNmM1NHBK
            Q2E4bUJpUzJvOUk1ajVhMDZGaHBQNzQKLS0tIGp2Q3UwcklCUElzNEhwenMxSzRK
            d25sSzU0aUpya2hCRiszQUF6K092SEkKnoN0DNEEFCWFv3bPazkKJi8F9foLthKu
            oPEDKnX3haRlYTJgiN4+xIlQB/K5U0FAs8ivTrh7UKHFghNJ0q6w5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-09T20:46:11Z"
    mac: ENC[AES256_GCM,data:upc6nI1ekQWYoM4i2HXQz3Kos6hyeMMxEwDXusOxnwL4KUPtoGYaf5IUH7/iy2YyL/pXxCmc5YrsxDrQ5+UUZcnqn5GOR03muNA7SYy1SMD3w9nNZ+BO79jZjR42O1DzbGA2SWbqcI2ycUO/h4UM7ZJyBqwHP+ZODiZmeZJYcnc=,iv:dHYKj4Hhlv5wzkXtUrbunzpfPqw1Mo71vncmpXbSWug=,tag:CmZ+8OYH3OZrJ7HI2o2btA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
