---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: immich-secret
    creationPolicy: Owner
  data:
