---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs
spec:
  storageClassName: immich-nfs
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NAS_ADDRESS}"
    path: "${NAS_BASE_URL}/media/software/applications/immich"
  # Note: The first two options are strictly for NFSv4.2
  mountOptions:
    - nfsvers=4
    - tcp
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: immich-nfs
  resources:
    requests:
      storage: 1Mi # Size does not matter
