---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: readarr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: readarr-secret
    creationPolicy: Owner
    template:
      data:
        READARR__AUTH__APIKEY: "{{ .API_KEY }}"
  dataFrom:
    - extract:
        key: Readarr
