---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name gatus-secret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # App
        DISCORD_WEBHOOK_URL: "{{ .DISCORD_WEBHOOK_URL }}"
        SECRET_DOMAIN: ${SECRET_DOMAIN}
  dataFrom:
  - extract:
      key: kv/cluster/discord
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name gatus-db-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: gatus-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        POSTGRES_URI: '{{ index . "pgbouncer-uri" }}'
  dataFrom:
  - extract:
      key: postgres-pguser-gatus
