---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stalwart
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: stalwart-secret
    creationPolicy: Owner
    template:
      data:
        ADMIN_SECRET: "{{ .ADMIN_SECRET }}"
  dataFrom:
    - extract:
        key: kv/cluster/default/stalwart
