---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stalwart
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: stalwart-secret
    creationPolicy: Owner
    template:
      data:
        values.yaml: |
          secrets:
            env:
              FALLBACK_ADMIN_SECRET: "{{ .ADMIN_SECRET }}"
              LDAP_BASE_DN: "{{ .LDAP_BASE_DN }}"

  dataFrom:
    - extract:
        key: kv/cluster/default/stalwart
    - extract:
        key: kv/cluster/security/lldap
