---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: radarr-secret
    creationPolicy: Owner
    template:
      data:
        RADARR__API_KEY: "{{ .API_KEY }}"
  dataFrom:
    - extract:
        key: kv/cluster/media/radarr
