---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: onlyoffice
spec:
  target:
    name: onlyoffice-secret
    template:
      data:
        POSTGRES_PASSWORD: '{{ .password }}'
        RABBITMQ_PASSWORD: '{{ .RABBITMQ_PASSWORD }}'
        secret: '{{ .ONLYOFFICE_SECRET }}'
  dataFrom:
    - extract:
        key: kv/cluster/default/onlyoffice
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault-backend
      rewrite:
        - regexp:
            source: "(.*)"
            target: "ONLYOFFICE_$1"
    - extract:
        key: postgres-pguser-onlyoffice
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
    - extract:
        key: kv/cluster/database/rabbitmq
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault-backend
      rewrite:
        - regexp:
            source: "(.*)"
            target: "RABBITMQ_$1"
