apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
  mariaDbRef:
    name: mariadb-galera
  schedule:
    cron: "*/1 * * * *"
    suspend: false
  maxRetention: 720h # 30 days
  storage:
    s3:
      bucket: backups
      prefix: mariadb
      endpoint: minio.minio.svc.cluster.local:9000
      region: us-east-1
      accessKeyIdSecretKeyRef:
        name: mariadb-secret
        key: access-key
      secretAccessKeySecretKeyRef:
        name: mariadb-secret
        key: secret-key
      tls:
        enabled: true
        caSecretKeyRef:
          name: mariadb-secret
          key: ca.crt
