---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mariadb-secret
    creationPolicy: Owner
    template:
      data:
        root_password: '{{ .MARIADB_password }}'
        access_key: '{{ .ACCESS_KEY }}'
        secret_key: '{{ .SECRET_KEY }}'
        ca.crt: '{{ index . "ca.crt" }}'
  dataFrom:
    - extract:
        key: MariaDB
      rewrite:
        - regexp:
            source: "(.*)"
            target: "MARIADB_$1"
    - extract:
        key: S3
    - extract:
        key: TrueNAS CA
