apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-secret
    key: root_password
    generate: false
  storage:
    size: 5Gi
    storageClassName: ceph-block
  replicas: 1
  image: "mariadb:11.7.2"
  imagePullPolicy: IfNotPresent
  maxScale:
    enabled: true
    auth:
      adminUsername: root
      adminPasswordSecretKeyRef:
        name: mariadb-secret
        key: root_password
      deleteDefaultAdmin: true
    connection:
      secretName: mxs-galera-conn
      port: 3306
  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 2Gi

  metrics:
    enabled: true
