---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: collabora
spec:
  refreshInterval: 5m
  target:
    name: collabora-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .COLLABORA_ADMIN_USER }}"
        password: "{{ .COLLABORA_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: kv/cluster/default/collabora
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault-backend
      rewrite:
        - regexp:
            source: "(.*)"
            target: "COLLABORA_$1"
