---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: affine
spec:
  target:
    name: affine-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: '{{ index . "pgbouncer-uri" }}'
        MAILER_HOST: '{{ .SMTP_HOST }}'
        MAILER_PORT: '{{ .SMTP_PORT }}'
        MAILER_USER: '{{ .SMTP_USERNAME }}'
        MAILER_PASSWORD: '{{ .SMTP_PASSWORD }}'
  dataFrom:
    - extract:
        key: kv/cluster/smtp
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault-backend
    - extract:
        key: kv/cluster/default/affine
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault-backend
    - extract:
        key: postgres-pguser-affine
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
