apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:y8qog4rTZ/RkLWWUMuzGK9Nhn7vuYtTnXGsjoWOVS9XzyO9DjUGUjJGlQckJT7nM8/AaaCR2qTIqjMxAN+rp767tIjZ0JHH04vAG6cigigbSpq/9/1dt0wCJHlADVg==,iv:HABGjpNJt0HUuOOdASVKjtXjAl1kOA3ZbPHJL4HoAl4=,tag:nSNJFVn50VAMCsRxHSsACw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:MLpCkhTRpQ==,iv:+gxoEA7FT4VSTTfpXf6efr2gx3Fte1NdjecXw2a5JkM=,tag:y42ONg3uRqsKqlOvvLh9Lw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:oVXy0DaSlVW9BMg355vexUge4UYbrQ==,iv:lJ4Hc2PqVGAhIv6TE3al+OquBkfVjluubBjHmR11hqE=,tag:EDhoqL4ZC4m6V0EO8ElCvA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:r32mLne3/bm+iwcfAXOYBN9h5jORkqFzzFvkyNH7/uGSuElA,iv:ycQ3N8Lqre3JNG21yuRykw9aYSMyNEW06cgp/KSwGkQ=,tag:vZ+SlfMosA9VwgyehAmlmw==,type:str]
    SECRET_DYNDNS: ENC[AES256_GCM,data:YXz8HlbnsYFDW1d8ki72wMjT,iv:Avl/7vdSvtds0cgkMgq1rCtvHALTLEM+I3TjRLiRHj8=,tag:NcAfjIhTcFe8SmbvPJKg7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWDlzVVF2QldRVTk1bzQw
            ZVNrSlZRSU1KelZjZ3dacnFjcHBQN3ZudjJjCnF5VXo1eWYreEtQb0x4Rk5yWjVu
            amJrcGxsN2VxbTI0bEQ0R3preUZFeDQKLS0tIE5weGRKWkwrSWJic0NUUVlVaW1F
            b0dJaDBsbURIWnFkMGVZN2s2RTY4M2cKIkwRmSVJ42rij9qPVWkQum9sQZAlCIaV
            mQXk/5zzL/cbKIpKERo4C0JdiC58M3lwq4H5NtLqXrDiQ1S8XPl2oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-11T22:26:21Z"
    mac: ENC[AES256_GCM,data:lYbkvHdKn1z0GOAr6GQFm3fiWQia6CiESjABBnaGNeIKr160z35RbNn0p9SCb8eo6+JLsd+jRB8fn5aUfcjQiSzdtbNfJMGEg6W9SL0r3AtTiyQ7e2PYvzR2CGyrjnPYGxxw0FbQOqe9lZWD21F2Q+xLYWkF6/uqauE7nMRAhWI=,iv:E0v1dPzVfiV+sI4Dvuk8vxcyPG0yaRva9VF3WWQAFdU=,tag:2oTwKLku2Seu50P6CC+sFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
