apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:6UPiVyZWG2yY+x7N0MJjKG9jb80ADlTug3UuGTlO1h+qQM1J5BQ7wTH5W4ewMb/9sELAUPLBFD7nRFRID+7eI86oRZWM/xURut4cAPq0mgp41dTGmsyZKRBvp9tjmA==,iv:jgnkOgw32kQgV3kPXK+aAJJwyQBQDo/T7Ux6fjBDRRE=,tag:xw5I4ONbYIUM4loVyxJV+Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:BSjigpNOHg==,iv:e4v63AY3lptKEm5j4a/ZvTmNl7L9m3d7y360qit79OE=,tag:zjWprW+D66q7vPiviEsPPA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:8QDmbIlvaq/UBdJZ8XDXGQub9jmNBg==,iv:KktyPZOQk2adcwCs5xuyc1NsKvvvhRhWkwCewBCVAi8=,tag:WH+Xw4dqw+eV+tuCfio70w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:+vuYehHHZOa3vVEsd1gPT1fNoWLpyHiNt1sXuNTuqchpad0q,iv:FhOus4CaMEgIwvYqJISJ3cWFAyUHNBNAyo9Gkchk6zs=,tag:tlWZQ2aun6HoEaD4Oy5e8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZjhERUlrS2YydDRXM2pW
            UzV5TWo1YTEvVEJ0V095VWxiWlZveGFMRlhrCjErTFJSUkQ4UTVRc2xmSTN5dHR3
            eVkyeDJ0Z1lETm16ejNVWmc1OHgzblkKLS0tIExsNlhacWUyaGptTUZrWDJITDJu
            RytneWZ6UU16amE2emNucGdyQnFqOTAKp8FfqbrIjwdyXkAfvURp/i3DYFcBObQC
            Mzm/ZcAcvdqbv/EORUx9hwRShHqDdpcsHS+nDyqGa//9SOt8jMcGkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-03T08:32:06Z"
    mac: ENC[AES256_GCM,data:ZZ0UoBaPt+NE25f9hpyawfW+GtAP1olzWOJSZ1XcXjCbW8SzDejfNmK3iOHBm7IditfsYgQnVKNCNXHJn13o9xPyvGG/rEBnIE6wWU8DhL1cmUp5zhlRY4VoFlfuNYmqCL5i5ZjrqbaC2OWaxAnweqll2H6wjRiNDhSicTvhmzQ=,iv:4GOceaaMkFEiKJEyJDMtAcCDefwhG5ZNZD8HJ/DUEVw=,tag:yyM2pgjDNR85Qyfa3hl3kQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
