---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Warsaw"
  CLUSTER_CIDR: "10.69.0.0/16"
  NODE_CIDR: "192.168.1.0/24"
  QBIT_ADDRESS: 192.168.1.250
  NAS_ADDRESS: 192.168.1.51
  NAS_BASE_URL: /mnt/eldorado
  PLEX_ADDRESS: 192.168.1.249
  POSTGRES_ADDRESS: 192.168.1.248
