# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app hoarder
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      hoarder:
        annotations:
          reloader.stakater.com/auto: 'true'
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/hoarder-app/hoarder
              tag: 0.21.0
            resources:
              requests:
                memory: 512Mi
              limits:
                memory: 600Mi
            env:
              DATA_DIR: /data
              MEILI_ADDR: http://meilisearch:7700
              NEXTAUTH_URL: https://hoarder.${SECRET_DOMAIN}
            envFrom:
              - secretRef:
                  name: hoarder-secret
    service:
      app:
        controller: hoarder
        ports:
          http:
            port: 3000
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          gethomepage.dev/name: *app
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: Personal
          gethomepage.dev/icon: hoarder.png
        hosts:
          - host: &host "hoarder.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /data
