---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slskd
spec:
  refreshInterval: 15m
  target:
    name: slskd-secret
    template:
      engineVersion: v2
      data:
        SLSKD_SLSK_USERNAME: "{{ .SLSKD_SLSK_USERNAME }}"
        SLSKD_SLSK_PASSWORD: "{{ .SLSKD_SLSK_PASSWORD }}"
  dataFrom:
    - extract:
        key: kv/cluster/media/slskd
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: vault-backend
      rewrite:
        - regexp:
            source: "(.*)"
            target: "SLSKD_$1"
