---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app slskd
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      slskd:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/slskd/slskd
              tag: 0.22.1@sha256:ab52af766b54b8a0f6b61969c77a2204ce4ef95f0217a627d09ebda8346c451c
            env:
              DOTNET_BUNDLE_EXTRACT_BASE_DIR: /tmp/.net
              TZ: ${TIMEZONE}
              SLSKD_APP_DIR: /config
              SLSKD_HTTP_PORT: &port 80
              SLSKD_NO_AUTH: true
              SLSKD_NO_HTTPS: true
              SLSKD_SLSK_LISTEN_PORT: &soulseekPort 50300
            envFrom:
              - secretRef:
                  name: slskd-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: ${NAS_UID}
        runAsGroup: ${NAS_GID}
        fsGroup: ${NAS_GID}
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: slskd
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${SLSKD_ADDRESS}
        ports:
          http:
            port: *port
          soulseek:
            enabled: true
            port: *soulseekPort
            protocol: TCP
    ingress:
      app:
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: *app
      config-file:
        type: secret
        name: slskd-secret
        globalMounts:
          - path: /config/slskd.yml
            subPath: slskd.yml
            readOnly: true
      tmp:
        type: emptyDir
      media:
        enabled: true
        type: nfs
        globalMounts:
          - path: /media
        server: "${NAS_ADDRESS}"
        path: "${NAS_BASE_URL}/media"
