---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./hr.yaml
  - ./es.yaml
  - ../../../../templates/volsync/
configMapGenerator:
  - name: slskd-configmap
    files:
      - slskd.yml=./resources/slskd.yml
generatorOptions:
  disableNameSuffixHash: true
