---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: mealie-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SMTP_HOST: "{{ .SMTP_HOST }}"
        SMTP_PORT: "{{ .SMTP_PORT }}"
        SMTP_USER: "{{ .SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
        SMTP_AUTH_STRATEGY: "TLS"
        SMTP_FROM_EMAIL: cluster+recipes@${SECRET_DOMAIN}
        SMTP_FROM_NAME: Mealie
        OIDC_AUTH_ENABLED: "true"
        OIDC_SIGNUP_ENABLED: "true"
        OIDC_CONFIGURATION_URL: "https://sso.${SECRET_DOMAIN}/application/o/mealie/.well-known/openid-configuration"
        OIDC_CLIENT_ID: "{{ .MEALIE_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .MEALIE_CLIENT_SECRET }}"
        OIDC_AUTO_REDIRECT: "false"
        OIDC_REMEMBER_ME: "true"
        OIDC_USER_GROUP: users
        OIDC_ADMIN_GROUP: Mealie Admins
  dataFrom:
    - extract:
        key: kv/cluster/default/mealie
      rewrite:
        - regexp:
            source: "(.*)"
            target: "MEALIE_$1"
    - extract:
        key: kv/cluster/smtp
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mealie-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: mealie-secret
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        POSTGRES_USER: '{{ index . "user" }}'
        POSTGRES_PASSWORD: '{{ index . "password" }}'
        POSTGRES_SERVER: '{{ index . "pgbouncer-host" }}'
        POSTGRES_PORT: '{{ index . "pgbouncer-port" }}'
        POSTGRES_DB: '{{ index . "dbname" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-mealie
