---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
spec:
  chart:
    spec:
      chart: mariadb-operator-crds
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
      version: "0.36.0"
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  interval: 30m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-operator
spec:
  dependsOn:
    - name: mariadb-operator-crds
  chart:
    spec:
      chart: mariadb-operator
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
      version: "0.36.0"
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  interval: 30m
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    webhook:
      cert:
        certManager:
          enabled: true
      serviceMonitor:
        enabled: true
