---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        ## Non Cluster resources
        HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_TAG }}"
        HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .CLUSTER_CLOUDFLARE_TUNNEL_ID }}"
        HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .CLOUDFLARE_API_KEY }}"
        HOMEPAGE_VAR_TRUENAS_API_TOKEN: "{{ .TRUENAS_API_KEY }}"
        ## Downloads
        HOMEPAGE_VAR_PROWLARR_TOKEN: "{{ .PROWLARR_API_KEY }}"
        HOMEPAGE_VAR_QBITTORRENT_USERNAME: "{{ .QBITTORRENT_username }}"
        HOMEPAGE_VAR_QBITTORRENT_PASSWORD: "{{ .QBITTORRENT_password }}"
        HOMEPAGE_VAR_RADARR_TOKEN: "{{ .RADARR_API_KEY }}"
        HOMEPAGE_VAR_SONARR_TOKEN: "{{ .SONARR_API_KEY }}"
        HOMEPAGE_VAR_LIDARR_TOKEN: "{{ .LIDARR_API_KEY }}"
        ## Media
        HOMEPAGE_VAR_JELLYFIN_TOKEN: "{{ .JELLYFIN_API_KEY }}"
        HOMEPAGE_VAR_IMMICH_TOKEN: "{{ .IMMICH_API_KEY }}"
        ## Observability
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_ADMIN_USER }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"
        ## Security
        HOMEPAGE_VAR_AUTHENTIK_TOKEN: "{{ .AUTHENTIK_TOKEN }}"
  dataFrom:
  - extract:
      key: kv/cluster/security/authentik
  - extract:
      key: kv/cluster/network/cloudflared
  - extract:
      key: kv/cluster/monitoring/grafana
  - extract:
      key: qBittorrent
    rewrite:
    - regexp:
        source: "(.*)"
        target: "QBITTORRENT_$1"
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: onepassword-connect
  - extract:
      key: Prowlarr
    rewrite:
    - regexp:
        source: "(.*)"
        target: "PROWLARR_$1"
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: onepassword-connect
  - extract:
      key: Lidarr
    rewrite:
    - regexp:
        source: "(.*)"
        target: "LIDARR_$1"
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: onepassword-connect
  - extract:
      key: Radarr
    rewrite:
    - regexp:
        source: "(.*)"
        target: "RADARR_$1"
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: onepassword-connect
  - extract:
      key: Sonarr
    rewrite:
    - regexp:
        source: "(.*)"
        target: "SONARR_$1"
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: onepassword-connect
  - extract:
      key: Jellyfin
    rewrite:
    - regexp:
        source: "(.*)"
        target: "JELLYFIN_$1"
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: onepassword-connect
  - extract:
      key: Immich
    rewrite:
    - regexp:
        source: "(.*)"
        target: "IMMICH_$1"
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: onepassword-connect
  - extract:
      key: TrueNAS
    rewrite:
    - regexp:
        source: "(.*)"
        target: "TRUENAS_$1"
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: onepassword-connect
