---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tandoor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tandoor-secret
    template:
      data:
        # App
        DB_ENGINE: django.db.backends.postgresql_psycopg2
        # DB_OPTIONS: '{"sslmode":"require"}'
        SECRET_KEY: "{{ .TANDOOR_SECRET_KEY }}"
        POSTGRES_USER: &dbUser '{{ .user }}'
        POSTGRES_PASSWORD: &dbPass '{{ .password }}'
        POSTGRES_HOST: &dbHost '{{ index . "pgbouncer-host" }}'
        POSTGRES_PORT: '{{ index . "pgbouncer-port" }}'
        POSTGRES_DB: &dbName '{{ .dbname }}'
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .superuser_password }}"
        # LDAP
        LDAP_AUTH: '1'
        AUTH_LDAP_SERVER_URI: 'ldap://lldap.security.svc.cluster.local:3890'
        AUTH_LDAP_BIND_DN: uid={{ .LLDAP_READONLY_ADMIN_USERNAME }},ou=people,DC=zed,DC=gay
        AUTH_LDAP_BIND_PASSWORD: '{{ .LLDAP_READONLY_ADMIN_PASSWORD }}'
        AUTH_LDAP_USER_SEARCH_BASE_DN: ou=people,dc=zed,dc=gay
  dataFrom:
    - extract:
        key: Tandoor
      rewrite:
        - regexp:
            source: "(.*)"
            target: "TANDOOR_$1"
    - extract:
        key: LLDAP
      rewrite:
        - regexp:
            source: "(.*)"
            target: "LLDAP_$1"
    - extract:
        key: postgres-pguser-tandoor
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
    - extract:
        key: postgres-pguser-postgres
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
      rewrite:
        - regexp:
            source: "(.*)"
            target: "superuser_$1"
