---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tandoor
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      enableServiceLinks: false
      securityContext:
        runAsUser: ${NAS_UID}
        runAsGroup: ${NAS_GID}
    controllers:
      tandoor:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          migrations:
            image:
              repository: vabene1111/recipes
              tag: 1.5.24@sha256:e790307a447f0a546df6bd16421f0b82b38ba2fdea52601d07143a54fd708db4
            envFrom: &envFrom
              - secretRef:
                  name: tandoor-secret
            command:
            - sh
            - -c
            - |
              set -e
              source /opt/recipes/venv/bin/activate
              echo "Updating database"
              python3 /opt/recipes/manage.py migrate
              python3 /opt/recipes/manage.py collectstatic_js_reverse
              python3 /opt/recipes/manage.py collectstatic --noinput
        containers:
          app:
            image:
              repository: ghcr.io/tandoorrecipes/recipes
              tag: 1.5.24
            env:
              COMMENT_PREF_DEFAULT: 0
              DEBUG: 1
              ENABLE_SIGNUP: 0
              FRACTION_PREF_DEFAULT: 0
              GUNICORN_MEDIA: 0
              MAX_OWNED_SPACES_PREF_DEFAULT: 1000
              SHOPPING_MIN_AUTOSYNC_INTERVAL: 5
              TANDOOR_PORT: &tandoorPort 8888
            envFrom: *envFrom
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /accounts/login/
                    port: *tandoorPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /accounts/login/
                    port: *tandoorPort
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 10m
                memory: 500Mi
              limits:
                memory: 750Mi
          nginx:
            image:
              repository: ghcr.io/nginxinc/nginx-unprivileged
              tag: 1.27.3-alpine
    service:
      app:
        controller: *app
        ports:
          http:
            port: *tandoorPort
          nginx:
            port: &nginxPort 8080
    ingress:
      app:
        className: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: external.rafaribe.com
          hajimari.io/icon: mdi:chef-hat
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Tandoor
          gethomepage.dev/description: Managing recipes, planned meals, shopping lists.
          gethomepage.dev/group: Applications
          gethomepage.dev/icon: tandoor.png
          gethomepage.dev/pod-selector: >-
            app in (
              tandoor
            )
        hosts:
          - host: tandoor.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
              - path: /media
                service:
                  identifier: app
                  port: *nginxPort
              - path: /static
                service:
                  identifier: app
                  port: *nginxPort
    persistence:
      config:
        existingClaim: *app
        advancedMounts:
          tandoor:
            app:
              - path: /opt/recipes/mediafiles
            nginx:
              - path: /media
      nginx-config:
        type: configMap
        name: tandoor-configmap
        advancedMounts:
          tandoor:
            nginx:
              - path: /etc/nginx/nginx.conf
                subPath: nginx-config
      django-js-reverse:
        type: emptyDir
        advancedMounts:
          tandoor:
            app:
              - path: /opt/recipes/cookbook/static/django_js_reverse
            migrations:
              - path: /opt/recipes/cookbook/static/django_js_reverse
      static:
        type: emptyDir
        advancedMounts:
          tandoor:
            app:
              - path: /opt/recipes/staticfiles
            nginx:
              - path: /static
            migrations:
              - path: /opt/recipes/staticfiles
      cache:
        type: emptyDir
        advancedMounts:
          tandoor:
            nginx:
              - path: /var/cache/nginx
