---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lidarr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: lidarr-secret
    creationPolicy: Owner
    template:
      data:
        LIDARR__API_KEY: "{{ .API_KEY }}"
  dataFrom:
    - extract:
        key: kv/cluster/media/lidarr
