
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 5m
  target:
    name: linkwarden-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        DATABASE_URL: '{{ index . "pgbouncer-uri" }}'
        NEXTAUTH_SECRET: "{{ .LINKWARDEN_NEXTAUTH_SECRET }}"
        AUTHELIA_CLIENT_ID: "{{ .LINKWARDEN_CLIENT_ID }}"
        AUTHELIA_CLIENT_SECRET: "{{ .LINKWARDEN_CLIENT_SECRET }}"
        AUTHELIA_CLIENT_SECRET_DIGEST: "{{ .LINKWARDEN_CLIENT_SECRET_DIGEST }}"
  dataFrom:
    - extract:
        key: Linkwarden
      rewrite:
        - regexp:
            source: "(.*)"
            target: "LINKWARDEN_$1"
    - extract:
        key: postgres-pguser-linkwarden
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: crunchy-pgo-secrets
