apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:X+j8f2xClGvYiauZbIoRpKqDCHUBoetzNelUJxmkJXh4KOilttCs7Q==,iv:GZAxDrtXGG86GpJclie84Q3ubCAmlZAkxA5hJVBBxA8=,tag:FrmtIam9opH6czN1DadW+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bld0ZjlIc0l4VmQ4dEdB
            TFdsN0xuU25jaWo0akQ5UlJaVXcxdERqdHcwCis5NXpYTzlPUlk5N1FkUkMwN29o
            VDJRbmVaanFBU0VYYjdoUnl0eFVyajAKLS0tIFJRYjNvaXpCdm91M3RQNnBLYkRL
            MXFCMDdlaXQ1YkVVZDNFM0dIdGp1TjQKiIMNoBotzQ7aQ1RoOHKHmpI4HAmz2ROt
            dAQvkzpkpB+4OhNNEXCGRM6cMSBseYyfuIVK1l3dLphI7CcgkuUC9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-17T18:54:50Z"
    mac: ENC[AES256_GCM,data:hG3yB6es2VFSkgyN0QRT0gr40BUGwAPgP4OSE3FWz/FyOsXk0laj0x0gS8vxs7GoV0q8hc/YWw+I7Oe3tfQmDrFwkVv4Mwq+vsskRTsaXBN55zjvSnrv2+xxI+UE/ORaDal+jDW536E8K8ZWpoSR+89nVSHDra4Jo1zbh1vayYs=,iv:1QGFxTlubN3R2o5TwjVKhzRlKWNxKTIDPnhcQXXPxwI=,tag:wIJxdjZ5HjZP66PoaCsmVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
