---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: lldap-secret
    creationPolicy: Owner
    template:
      data:
        LLDAP_JWT_SECRET: "{{ .JWT_SECRET }}"
        LLDAP_LDAP_USER_PASS: "{{ .LDAP_USER_PASS }}"
        LLDAP_LDAP_BASE_DN: "{{ .LDAP_BASE_DN }}"
  dataFrom:
    - extract:
        key: kv/cluster/security/lldap
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: lldap
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        LLDAP_DATABASE_URL: '{{ .pgbouncer-uri }}'
  dataFrom:
  - extract:
      key: postgres-pguser-authentik
