# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app linkwarden
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
    controllers:
      linkwarden:
        annotations:
          reloader.stakater.com/auto: 'true'
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/linkwarden/linkwarden
              tag: v2.8.4
            resources:
              requests:
                memory: 512Mi
              limits:
                memory: 600Mi
            env:
              NEXTAUTH_URL: https://linkwarden.${SECRET_DOMAIN}/api/v1/auth
              STORAGE_FOLDER: "config" # Will always end up as /data/STOREAGE_FOLDER so eg /data/config
              HOME: /data/config
              NEXT_PUBLIC_AUTHELIA_ENABLED: "true"
              AUTHELIA_WELLKNOWN_URL: "https://auth.${SECRET_DOMAIN}/.well-known/openid-configuration"
            envFrom:
              - secretRef:
                  name: linkwarden-secret
    service:
      app:
        controller: linkwarden
        ports:
          http:
            port: 3000
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          gethomepage.dev/name: *app
          gethomepage.dev/enabled: 'true'
          gethomepage.dev/group: Personal
          gethomepage.dev/icon: linkwarden.png
        hosts:
          - host: &host "linkwarden.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /data/config
      next-cache:
        type: emptyDir
        globalMounts:
          - path: /data/.next/cache
