---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 3.10.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    release:
      version: "4.0.0"
    mayastor:
      enabled: true
      hostpathClass:
        enabled: true
        name: openebs-mayastor
        isDefaultClass: true
        basePath: /var/openebs/local
    ndm:
      enabled: false
    ndmOperator:
      enabled: false
