---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ocis
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      ocis:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-config:
            image:
              repository: docker.io/owncloud/ocis
              tag: 7.0.0
            command:
              - /bin/sh
              - -c
            args:
              - |
                if [ ! -f /etc/ocis/ocis.yaml ]; then ocis init; else exit 0; fi
            env:
              OCIS_INSECURE: true

        containers:
          ocis:
            image:
              repository: docker.io/owncloud/ocis
              tag: 7.0.0
            env:
              TZ: "${TIMEZONE}"
              OCIS_INSECURE: true
              STORAGE_USERS_DRIVER: s3ng
              STORAGE_SYSTEM_DRIVER: ocis
              STORAGE_USERS_S3NG_ENDPOINT: "https://${NAS_ADDRESS}:9000"
              STORAGE_USERS_S3NG_REGION: default
              STORAGE_USERS_S3NG_BUCKET: ocis
              OCIS_URL: "https://files.${SECRET_DOMAIN}"
              PROXY_TLS: false
              DEMO_USERS: false
              OCIS_LOG_LEVEL: info
              OCIS_LOG_COLOR: true
              OCIS_LOG_PRETTY: true
              PROXY_HTTP_ADDR: 0.0.0.0:9200
              PROXY_DEBUG_ADDR: 0.0.0.0:9205
              #NOTIFICATIONS_SMTP_HOST: "${SMTP_RELAY_HOST}"
              #NOTIFICATIONS_SMTP_PORT: "${SMTP_RELAY_PORT}"
              NOTIFICATIONS_SMTP_SENDER: "ocis@${SECRET_DOMAIN}"
              #NOTIFICATIONS_SMTP_INSECURE: true
              OCIS_OIDC_ISSUER: "https://auth.${SECRET_DOMAIN}"
              WEB_OIDC_METADATA_URL: "https://auth.${SECRET_DOMAIN}/.well-known/openid-configuration"
              WEB_OIDC_CLIENT_ID: ocis
              PROXY_CSP_CONFIG_FILE_LOCATION: &csp /etc/ocis/csp.yaml
              # docs: https://doc.owncloud.com/ocis/next/deployment/services/s-list/proxy.html#automatic-role-assignments
              PROXY_OIDC_ACCESS_TOKEN_VERIFY_METHOD: none
              PROXY_OIDC_REWRITE_WELLKNOWN: true
              PROXY_AUTOPROVISION_ACCOUNTS: true
              WEB_OIDC_SCOPE: "openid profile email groups"
              PROXY_USER_OIDC_CLAIM: "preferred_username"

              # Authelia OIDC
              # Auto role assignment:
              # docs: https://doc.owncloud.com/ocis/next/deployment/services/s-list/proxy.html#automatic-role-assignments
              PROXY_ROLE_ASSIGNMENT_DRIVER: default
              PROXY_ROLE_ASSIGNMENT_OIDC_CLAIM: groups
            envFrom:
              - secretRef:
                  name: ocis-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: [ALL]
        pod:
          securityContext:
            runAsUser: 586
            runAsGroup: 586
            runAsNonRoot: true
            fsGroup: 586
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: ocis
        ports:
          http:
            port: 9200
            primary: true
          metrics:
            port: 9205
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: metrics
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            add_header Cache-Control "no-store";
            add_header Pragma "no-cache";
            add_header X-Frame-Options "SAMEORIGIN";
            add_header X-XSS-Protection "1; mode=block";
        hosts:
          - host: &host files.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /etc/ocis
            subPath: config
          - path: /var/lib/ocis
            subPath: data
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
      certs:
        type: configMap
        name: public-bundle
        globalMounts:
          - path: /etc/ssl/certs
            readOnly: true
      config-proxy:
        type: configMap
        name: ocis-configmap
        globalMounts:
          - path: /etc/ocis/proxy.yaml
            subPath: proxy.yaml
            readOnly: true
          - path: *csp
            subPath: csp.yaml
            readOnly: true
